repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.9
  hooks:
  - id: ruff
    args: [ --fix ]
  - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.12.0
  hooks:
  - id: mypy
    additional_dependencies: [types-tabulate, types-docutils]
    args: [--ignore-missing-imports, --check-untyped-defs]
- repo: local
  hooks:
  - id: check-names
    name: Check for agent-instance names
    description: Verifies that we are not accidentally using names of agents in the template, or vice versa
    entry: make check-names
    language: system
    pass_filenames: false
    always_run: true
  - id: check-markdown-links
    name: Check markdown links
    description: Verifies all relative links in markdown files resolve correctly
    entry: python3 scripts/precommit/check_markdown_links.py
    language: system
    types: [markdown]
    pass_filenames: true
    # Exclude example files which intentionally have broken links
    exclude: ^projects/.*/examples/.*$
  - id: check-task-links
    name: Check task symlinks
    description: Verifies task files have exactly one valid symlink in a state directory
    entry: python3 scripts/precommit/check_task_links.py --type tasks
    language: system
    pass_filenames: false
    always_run: true
